### ISSUE TITLE
Gosu does not support 64-bit Ruby on Windows

### ISSUE THREAD

**Issue by jlnr** [jlnr/gosu#248]
...but that's probably only a matter of me precompiling it with RubyInstaller's 64-bit Ruby 2.0.0 :)

**Comment by shviller** [comment]
FWIW, I'm still getting the same error messages as people in #233:

 >gem install gosu --platform=x64-mingw32
 ...
 This gem is not meant to be installed on Windows. Instead, please use:
 gem install gosu --platform=i386-mingw32
 
 extconf failed, exit code 1

>gem install gosu --platform=i386-mingw32
...
1 gem installed
>ruby -e"require 'gosu'"
cannot load such file -- gosu.so (LoadError)

**Comment by jlnr** [comment]
This bug has been fixed in git, but I've been slower with releasing 0.8.7 than planned (as usual).

The manual fix is to download this file here:

https://raw.githubusercontent.com/jlnr/gosu/b3239d19ffc347c1e998af124ebcd1b6e34e35c9/lib/gosu.rb

And overwrite the file at the path that `gem which gosu.rb` prints on the command line with the downloaded file.

**Comment by TieSoul** [comment]
The manual fix is not working for me, it errors with the message 

```C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/gosu-0.8.6-x64-mingw32/lib/gosu.rb:13:in '<top (required)>': undefined local variable or method 'suffix' for main:Object (NameError)
	from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from C:/Users/thijsel/RubymineProjects/raytracer/tracer.rb:1:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'```

**Comment by jlnr** [comment]
Ouch, that is correct. I must have messed up this commit.

**Comment by jlnr** [comment]
@TieSoul I've messed up the commit on Windows last time, please use this file instead: https://github.com/jlnr/gosu/blob/master/lib/gosu.rb

**Comment by shviller** [comment]
I must be missing something; there should be more to this than taking an 0.8.6 installation and replacing one file. I'm still getting the same `cannot load such file -- gosu.so (LoadError)`, and it no surprise, since it works by adding `lib64` to the path, and this dir simply doesn't exist in the 0.8.6 gem I've got from rubygems.

**Comment by jlnr** [comment]
Then you must have gotten the wrong gem. There are two Windows gems, one for 32-bit and one for 64-bit Ruby:

https://rubygems.org/gems/gosu

This will be the same with Gosu 0.8.7.

**Comment by shviller** [comment]
See above.
```
>gem install gosu --platform=x64-mingw32
...
This gem is not meant to be installed on Windows. Instead, please use:
gem install gosu --platform=i386-mingw32
```

**Comment by jlnr** [comment]
> This gem is not meant to be installed on Windows. Instead, please use:

Looks like a RubyGems bug, because this message is definitely coming from the `platform=ruby` gem. Sigh... :( @shviller - you are using the RubyInstaller 2.1 x64 build, right? I'll try to reproduce the issue.

**Comment by shviller** [comment]
Yup, that's what I'm using. To be exact,
```
>ruby --version
ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]
```
and `DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe`

**Comment by jlnr** [comment]
```
C:\Users\jlnr\Desktop>gem -v
2.4.5

C:\Users\jlnr\Desktop>gem install gosu
Fetching: gosu-0.8.6-x64-mingw32.gem (100%)
Successfully installed gosu-0.8.6-x64-mingw32
1 gem installed
```
…
```
C:\Users\jlnr\Desktop>gem install gosu --platform=x64-mingw32
Fetching: gosu-0.8.6-x64-mingw32.gem (100%)
Successfully installed gosu-0.8.6-x64-mingw32
1 gem installed
```

Which version of RubyGems are you using?

**Comment by shviller** [comment]
```
>gem --version
2.2.3
```
It was a manual update from 2.2.2 due to [the certificate issue](https://github.com/oneclick/rubyinstaller/issues/249). Here's what it tells me:
```
>gem install gosu
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing gosu:
        ERROR: Failed to build gem native extension.

    c:/Programs/Programming/Ruby215/bin/ruby.exe extconf.rb
This gem is not meant to be installed on Windows. Instead, please use:
gem install gosu --platform=i386-mingw32
```

**Comment by jlnr** [comment]
There certificate issue is a mess. I've "fixed" it by dropping a batch script on my desktop that sets `SSL_CERT_FILE` to a custom downloaded PEM file.
Can you try to update to 2.4.5?

**Comment by shviller** [comment]
That finally did the trick. Didn't expect a seemingly working version of rubygems to trip me up like this. Thank you so much!

**Comment by jlnr** [comment]
No worries, that's good to hear! I've just pushed Gosu 0.8.7 too, so you shouldn't have to mess with the `gosu.rb` file anymore :)

**Comment by shviller** [comment]
Confirming, 0.8.7 is launching just fine. Thank you!
